Task 5 (LS3): Implement a program which, (a) given one of the feature models and (b) a value k,
– creates (and saves) a label-label similarity matrix,
– performs a user selected dimensionality reduction technique (SVD, NNMF, LDA, k-means) on this label-label
similarity matrix,
– stores the latent semantics in a properly named output file
– lists label-weight pairs, ordered in decreasing order of weights

In [1]:
FEATURE_SPACE = input("Provide a feature space [color, hog, avgpool, layer3, fc, resnet_output].")

DIM_REDUCTION = input("Provide a dimensionality reduction technique [svd, nnmf, lda, kmeans].")

K = int(input("Enter K, the top K latent semantics to extract for the selected feature space."))


In [2]:
import numpy as np
from utils.database_utils import retrieve
from feature_models.feature_matrix.label_label_similarity import LabelLabelSimilarity

In [3]:
from utils.database_utils import retrieve
feature_vectors = retrieve(f'{FEATURE_SPACE}.pt')
formatter = LabelLabelSimilarity(feature_vectors)
label_feature_vectors = formatter.get_matrix()
print("Generating top-", K, " latent semantics under ", FEATURE_SPACE, " feature space using: ", DIM_REDUCTION)

Generating top- 5  latent semantics under  fc  feature space using:  lda


In [4]:
if DIM_REDUCTION == "svd":
    from feature_reducers.svd import SVDReducer
    reducer = SVDReducer


elif DIM_REDUCTION == "nnmf":
    from feature_reducers.nnmf import NNMFReducer
    reducer = NNMFReducer

elif DIM_REDUCTION == "lda":
    from feature_reducers.lda import LDAReducer
    reducer = LDAReducer

else:
    # kmeans.
    from feature_reducers.kmeans import KMeansReducer
    reducer = KMeansReducer

reducer = reducer(label_feature_vectors, K)

latent_semantics = reducer.reduce_features(label_feature_vectors)
print("Top K latent semantics: ")
print(latent_semantics)
print("Shape: ", latent_semantics.shape)

Top K latent semantics: 
[[0.42613829 0.01857969 0.51812439 0.01857882 0.01857882]
 [0.45072449 0.01996679 0.48936742 0.01997065 0.01997065]
 [0.01504904 0.01468253 0.94116883 0.0145498  0.0145498 ]
 [0.45659912 0.02367698 0.47573646 0.02199372 0.02199372]
 [0.34335432 0.01395416 0.6150294  0.01383106 0.01383106]
 [0.0176635  0.20453029 0.74374408 0.01703107 0.01703107]
 [0.26857016 0.00926907 0.70465409 0.00875334 0.00875334]
 [0.00892397 0.00883633 0.96503572 0.00860199 0.00860199]
 [0.1942142  0.01298347 0.76735347 0.01272443 0.01272443]
 [0.01188538 0.01166592 0.95327484 0.01158693 0.01158693]
 [0.01558217 0.01542846 0.93821996 0.01538471 0.01538471]
 [0.57188151 0.01638145 0.37979542 0.01597081 0.01597081]
 [0.01715008 0.14028482 0.80884214 0.01686148 0.01686148]
 [0.00993728 0.00970769 0.96100866 0.00967318 0.00967318]
 [0.00989476 0.00990204 0.96068544 0.00975888 0.00975888]
 [0.01147634 0.01129814 0.95501139 0.01110707 0.01110707]
 [0.00915933 0.00902164 0.96392009 0.00894947 0